services:
  server:
    build:
      context: .
    env_file:
      - .env
    volumes:
       - db_data_sqlite:/var/lib/kutt
       - custom:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
    ports:
      - ${PORT:-3001}:${PORT:-3001}
volumes:
  db_data_sqlite:
  custom:
